# Generated by Django 3.2.6 on 2021-08-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('assg_user', models.TextField()),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.tile')),
            ],
        ),
    ]
