# Generated by Django 3.2.6 on 2021-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='launchdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
