# Generated by Django 3.2.6 on 2021-08-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tile_launchdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assg_user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.CharField(max_length=5000),
        ),
    ]
